# Generated by Django 3.2.13 on 2023-05-21 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20230521_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='total_likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
